### ISSUE TITLE
差点被自动BID

### ISSUE THREAD

**Issue by frhhh** [luoyeETH/blur_bid_alert#1]
配置文件自动bid为off，监控地址留的默认的，系统能读取当前积分和BID情况，但是自动bid功能未关闭。。。直接奔着Monsuta下了几单，悬崖勒马被我手动取消了。感觉自动BID参数并没有正确读取。。。

**Comment by luoyeETH** [comment]
只有两个参数，一个自动撤单一个自动签名，没有自动bid参数。如果没开签名，撤单后的降价bid因为不会实际签名不会生效

**Comment by luoyeETH** [comment]
监控地址应该填自己的，默认是我的地址，我bid了Monsuta

**Comment by frhhh** [comment]
对，这个逻辑很奇怪。虽然地址是你的，为何监控打印的信息依然是我小狐狸对应的地址。另外bid签名参数为off的情况，为何还会自动去bid Monsuta。也就是监控信息的地址，和触发购买行为依据的地址，并不一致？

**Comment by luoyeETH** [comment]
> 

按道理来说，没填你自己的地址，获取不到你的bid信息，打印出的应该也是监控地址的信息。  
填好数据以及弹出小狐狸，是因为开启了自动cancel，在撤单后一般需要再补回来，这个过程主要是省事，不然还要自己重填，如果没开自动签名实际上没影响的。  
通常监控地址肯定要和自己地址一致，因为是监控自己的bid有没有出现异常，然后再做进一步处理。

**Comment by frhhh** [comment]
嗯嗯，这个逻辑我明白，主要是以下几点：
1. 能打印出我的bid信息，是因为程序在唤起我小狐狸并且密码错误后，我手动输入了正确的密码；
2. 比较疑惑的是经过1操作后，为何打印出来的数据就不是默认地址了（你的地址），而是使用了浏览器小狐狸的关联地址；
3. 自动补回这个动作，又恢复到依据默认地址（你的地址）行为判断补回动作了；
4. config.ini的默认内容里没有自动不会相关控制参数，可以考虑写上去；

**Comment by luoyeETH** [comment]
1和2因为我没有操作过，可能会有一些异常。三和四可以在配置文件里多加一个参数

**Comment by frhhh** [comment]
注意到参数表马上就更新了说明，这效率太神速了！

关于1和2，读了一下代码，如果没理解错的话，积分相关信息是直接读取当前窗口登录的Blur钱包地址的积分，并不是直接读取配置表里的地址。所以当配置表里的钱包地址与当前窗口登录blur的钱包地址不一致时，会出现我所说的情况。

另外，0.6的程序包和源码好像不是同一个版本，程序包版本貌似新一点。是传错了吗？

**Comment by luoyeETH** [comment]
已更新

**Comment by frhhh** [comment]
感谢大佬！这个issue我先关了，后续可能自己优化一些功能然后提供点建议。目前Blur Bot太卷了 = = 还容易被庄家割韭菜。
